esphome:
  name: wetterstation
  friendly_name: Wetterstation

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CEnB4ZI7MQ3azwDl1EQFWGEn7/+mmnS4YRBQq1HBUKY="

ota:
  - platform: esphome
    password: "e50e2b1f7ccb9611aa5a24b421a19768"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wetterstation Fallback Hotspot"
    password: "tzuzFbpnvIG4"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

captive_portal:

i2c:
  id: bus_a
  sda: D3
  scl: D4
  scan: true

sensor:
  - platform: bme280_i2c
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: "BME280 Temperatur"
      id: wstemp
      oversampling: 16x
    pressure:
      name: "BME280 Druck"
      id: wsdruck
    humidity:
      name: "BME280 Luftfeuchte"
      id: wsfeucht
    update_interval: 60s
